### ISSUE TITLE
Build fails looking for <filesystem> header

### ISSUE THREAD

**Issue by stevenbell** [matteodelabre/vnsee#29]
I've probably just missed some basic configuration option, but 0d94c7f39b817c3cb0ea921fc41e9ee702f90295 adds the `#include <filesystem>` header, which causes my build to fail:

```
[ 39%] Building CXX object CMakeFiles/vnsee.dir/src/rmioc/device.cpp.o
/home/steven/Documents/projects/remarkable/vnsee/src/rmioc/device.cpp:6:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
```

Do I need to enable C++17 support somewhere?

I've got the recommended toolchain installed: `oecore-x86_64-cortexa9hf-neon-toolchain-zero-gravitas-1.8-23.9.2019` 

```
$ arm-oe-linux-gnueabi-gcc --version
arm-oe-linux-gnueabi-gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
```

**Comment by matteodelabre** [comment]
Thanks for bringing this to my attention. I was using the Toltec toolchain, which provides a more recent version of GCC as compared to the original official toolchain. The old GCC version (7.3.0) has incomplete C++17 support, in particular with respect to `std::filesystem`. I’ll look into fixing the build with GCC 7.3.0 or, if that’s too difficult, I’ll update the build instructions to refer to the Toltec toolchain.

**Comment by matteodelabre** [comment]
I have updated the [build guide](https://github.com/matteodelabre/vnsee/blob/master/docs/build.md) with instructions on using the Toltec toolchain to complete the build.
